import { t } from '@/i18n';
import type { IconTexture, IconThemeDraft } from '@/stores/iconThemeStore';

export interface ThemeApp {
    id:     string;
    label:  string;
    icon:   string;
    accent: string;
}

export const THEME_APPS: ThemeApp[] = [
    { id: 'phone',       label: 'Phone',        icon: 'phone',       accent: '#34c759' },
    { id: 'messages',    label: 'Messages',     icon: 'messages',    accent: '#34c759' },
    { id: 'mail',        label: 'Mail',         icon: 'mail',        accent: '#0a84ff' },
    { id: 'maps',        label: 'Maps',         icon: 'maps',        accent: '#f0c43a' },
    { id: 'compass',     label: 'Compass',      icon: 'compass',     accent: '#1c1c1e' },
    { id: 'camera',      label: 'Camera',       icon: 'camera',      accent: '#1c1c1e' },
    { id: 'photos',      label: 'Photos',       icon: 'photos',      accent: '#ffffff' },
    { id: 'music',       label: 'Music',        icon: 'music',       accent: '#fa233b' },
    { id: 'weather',     label: 'Weather',      icon: 'weather',     accent: '#5ac8fa' },
    { id: 'clock',       label: 'Clock',        icon: 'clock',       accent: '#1c1c1e' },
    { id: 'calendar',    label: 'Calendar',     icon: 'calendar',    accent: '#ffffff' },
    { id: 'notes',       label: 'Notes',        icon: 'notes',       accent: '#fec547' },
    { id: 'voicememos',  label: 'Voice Memos',  icon: 'voicememos',  accent: '#ff3b30' },
    { id: 'bank',        label: 'Bank',         icon: 'bank',        accent: '#00b894' },
    { id: 'health',      label: 'Health',       icon: 'health',      accent: '#ff2d55' },
    { id: 'documents',   label: 'Files',        icon: 'documents',   accent: '#3478f6' },
    { id: 'groups',      label: 'Groups',       icon: 'groups',      accent: '#6c63ff' },
    { id: 'birdy',       label: 'Squawk',       icon: 'birdy',       accent: '#1d9bf0' },
    { id: 'services',    label: 'Services',     icon: 'services',    accent: '#16b8a6' },
    { id: 'pages',       label: 'Pages',        icon: 'pages',       accent: '#fbc02d' },
    { id: 'review',      label: 'Review',       icon: 'review',      accent: '#e03131' },
    { id: 'marketplace', label: 'Marketplace',  icon: 'marketplace', accent: '#0a84ff' },
    { id: 'mdt',         label: 'MDT',          icon: 'mdt',         accent: '#1d4ed8' },
    { id: 'emsmdt',      label: 'EMS',          icon: 'emsmdt',      accent: '#e11d48' },
    { id: 'dojmdt',      label: 'DOJ',          icon: 'dojmdt',      accent: '#6d28d9' },
    { id: 'racing',      label: 'Racing',         icon: 'racing',      accent: '#0bf2b4' },
    { id: 'darkchat',    label: 'Dark Chat',    icon: 'darkchat',    accent: '#1c1c1e' },
    { id: 'cherry',      label: 'Cherry',       icon: 'cherry',      accent: '#f0285a' },
    { id: 'photogram',   label: 'Photogram',    icon: 'photogram',   accent: '#d62976' },
    { id: 'garages',     label: 'Garages',      icon: 'garages',     accent: '#6e5cf2' },
    { id: 'homes',       label: 'Homes',        icon: 'homes',       accent: '#12b866' },
    { id: 'ryde',        label: 'Ryde',         icon: 'ryde',        accent: '#1c1c1e' },
    { id: 'radio',       label: 'Radio',        icon: 'radio',       accent: '#30b0c7' },
    { id: 'stocks',      label: 'Stocks',       icon: 'stocks',      accent: '#16c784' },
    { id: 'settings',    label: 'Settings',     icon: 'settings',    accent: '#8e8e93' },
    { id: 'appstore',    label: 'App Store',    icon: 'appstore',    accent: '#0a84ff' },
    { id: 'calculator',  label: 'Calculator',   icon: 'calculator',  accent: '#333335' },
    { id: 'passwords',   label: 'Passwords',    icon: 'passwords',   accent: '#1c1c1e' },
    { id: 'cookie',      label: 'Cookie',       icon: 'cookie',      accent: '#c77d2e' },
    { id: 'wordle',      label: 'Penta',        icon: 'wordle',      accent: '#6aaa64' },
    { id: 'flappy',      label: 'Flappy',       icon: 'flappy',      accent: '#4ec0ca' },
    { id: 'blocks',      label: 'Blocks',       icon: 'blocks',      accent: '#7c4dff' },
    { id: 'casino',      label: 'Casino',       icon: 'casino',      accent: '#0f5132' },
    { id: 'climber',     label: 'Climber',      icon: 'climber',     accent: '#8bc34a' },
    { id: 'connectfour', label: 'Connect 4',    icon: 'connectfour', accent: '#1e66d0' },
    { id: 'chess',       label: 'Chess',        icon: 'chess',       accent: '#3b3b3b' },
    { id: 'battleship',  label: 'Battleship',   icon: 'battleship',  accent: '#17a0b5' },
    { id: 'vibez',       label: 'Vibez',        icon: 'vibez',       accent: '#a855f7' },
    { id: 'weazelnews',  label: 'Weazel News',  icon: 'weazelnews',  accent: '#c8102e' },
    { id: 'streaks',     label: 'Streaks',      icon: 'streaks',     accent: '#ff7a1a' },
].sort((a, b) => a.label.localeCompare(b.label));

const PREVIEW_IDS = ['phone', 'mail', 'maps', 'music', 'weather', 'notes', 'photogram', 'settings'];

export const PREVIEW_APPS: ThemeApp[] = PREVIEW_IDS
    .map(id => THEME_APPS.find(app => app.id === id))
    .filter((app): app is ThemeApp => app !== undefined);

export const SWATCH_PREVIEW_APPS: ThemeApp[] = PREVIEW_APPS.slice(0, 3);

export const GLYPH_NAMES: string[] = [
    'appstore', 'appstore_cloud', 'appstore_download', 'appstore_gift', 'bank', 'bank_coins',
    'bank_piggy', 'bank_vault', 'battleship', 'birdy', 'birdy_egg', 'birdy_hash', 'birdy_megaphone',
    'blackjack', 'blocks', 'blocks_box', 'blocks_layers', 'blocks_puzzle', 'blocks_wall',
    'calc_divide', 'calc_percent', 'calc_plus', 'calculator', 'calendar', 'calendar_check',
    'calendar_clock', 'calendar_range', 'camera', 'camera_flash', 'camera_lens', 'camera_switch',
    'cards_club', 'cards_deck', 'cards_diamond', 'cards_dice', 'casino', 'cherry', 'cherry_fruit',
    'cherry_hands', 'cherry_rose', 'cherry_spark', 'chess', 'chess_brain', 'chess_castle',
    'chess_shield', 'chess_swords', 'climber', 'climber_flag', 'climber_snow', 'climber_trees',
    'clock', 'clock_alarm', 'clock_hourglass', 'clock_timer', 'compass', 'compass_crosshair',
    'compass_locate', 'compass_needle', 'connectfour', 'cookie', 'cookie_cake', 'cookie_candy',
    'cookie_donut', 'cookie_icecream', 'darkchat', 'darkchat_hidden', 'darkchat_lock',
    'darkchat_shield', 'darkchat_skull', 'documents', 'files_archive', 'files_clip', 'files_file',
    'files_folder_open', 'findfriends', 'flappy', 'flappy_cloudy', 'flappy_joystick',
    'flappy_rocket', 'four_columns', 'four_dot', 'four_target', 'friends_satellite', 'friends_scan',
    'friends_search', 'garage_bike', 'garage_car', 'garage_truck', 'garages', 'groups',
    'groups_contact', 'groups_person', 'groups_round', 'health', 'health_activity',
    'health_dumbbell', 'health_pill', 'health_stethoscope', 'home_bed', 'home_building',
    'home_door', 'homes', 'mail', 'mail_box', 'mail_inbox', 'mail_open', 'map_navigation',
    'map_pin', 'map_pinned', 'map_route', 'maps', 'market_basket', 'market_cart', 'market_package',
    'market_tag', 'marketplace', 'mdt', 'emsmdt', 'dojmdt', 'message_bubble', 'message_more', 'message_send',
    'message_text',
    'messages', 'music', 'music_disc', 'music_headphones', 'music_playlist', 'music_wave',
    'news_earth', 'news_podcast', 'news_rss', 'news_tv', 'notes', 'notes_list', 'notes_notebook',
    'notes_pen', 'pages', 'pages_book', 'pages_bookmark', 'pages_scroll', 'pass_finger', 'pass_key',
    'pass_lock', 'pass_shield', 'passwords', 'phone', 'phone_call', 'phone_headset',
    'phone_incoming', 'phone_outgoing', 'photogram', 'photogram_film', 'photogram_gallery',
    'photogram_grid', 'photogram_sparkles', 'photos', 'photos_frame', 'photos_gallery',
    'photos_images', 'racing', 'radio', 'radio_antenna', 'radio_boombox', 'radio_speaker',
    'radio_tower',
    'rail_ticket', 'rail_track', 'rail_tram', 'review', 'review_half', 'review_medal',
    'review_thumb', 'ryde', 'ryde_bus', 'ryde_taxi', 'ryde_waypoints', 'safari', 'safari_bookmark',
    'safari_link', 'safari_search', 'safari_window', 'services', 'services_badge',
    'services_hammer', 'services_hardhat', 'settings', 'settings_cog', 'settings_sliders',
    'settings_toggle', 'settings_wrench', 'ship_anchor', 'ship_sail', 'ship_waves', 'ship_wheel',
    'stocks', 'stocks_bars', 'stocks_candles', 'stocks_down',
    'stocks_line', 'streaks', 'streaks_calendar', 'streaks_check', 'streaks_kindling', 'vibez',
    'vibez_clapper', 'vibez_play', 'vibez_tv', 'voice_lines', 'voice_mailbox', 'voice_vocal',
    'voicememos', 'wallet', 'wallet_card', 'wallet_cash', 'wallet_coin', 'wallet_receipt',
    'weather', 'weather_cloud', 'weather_rain', 'weather_snow', 'weather_sun', 'weazelnews',
    'wordle', 'wordle_grid', 'wordle_spell', 'wordle_type',
];

const GLYPH_LABELS: Record<string, string> = {
    appstore_cloud:     'Cloud Download',
    appstore_download:  'Download',
    appstore_gift:      'Gift',
    bank_coins:         'Coins',
    bank_piggy:         'Piggy Bank',
    bank_vault:         'Vault',
    birdy_egg:          'Egg',
    birdy_hash:         'Hashtag',
    birdy_megaphone:    'Megaphone',
    blocks_box:         'Box',
    blocks_layers:      'Layers',
    blocks_puzzle:      'Puzzle Piece',
    blocks_wall:        'Brick Wall',
    calc_divide:        'Divide',
    calc_percent:       'Percent',
    calc_plus:          'Plus',
    calendar_check:     'Booked Day',
    calendar_clock:     'Scheduled',
    calendar_range:     'Date Range',
    camera_flash:       'Camera Flash',
    camera_lens:        'Camera Lens',
    camera_switch:      'Flip Camera',
    cards_club:         'Card Club',
    cards_deck:         'Card Deck',
    cards_diamond:      'Card Diamond',
    cards_dice:         'Dice',
    cherry_fruit:       'Cherries',
    cherry_hands:       'Caring Heart',
    cherry_rose:        'Flower',
    cherry_spark:       'Spark',
    chess_brain:        'Brain',
    chess_castle:       'Castle',
    chess_shield:       'Half Shield',
    chess_swords:       'Swords',
    climber_flag:       'Summit Flag',
    climber_snow:       'Snowy Peak',
    climber_trees:      'Trees',
    clock_alarm:        'Alarm Clock',
    clock_hourglass:    'Hourglass',
    clock_timer:        'Timer',
    compass_crosshair:  'Crosshair',
    compass_locate:     'Locate Me',
    compass_needle:     'Compass Needle',
    cookie_cake:        'Cake Slice',
    cookie_candy:       'Candy',
    cookie_donut:       'Donut',
    cookie_icecream:    'Ice Cream',
    darkchat_hidden:    'Hidden Eye',
    darkchat_lock:      'Padlock',
    darkchat_shield:    'Shield Check',
    darkchat_skull:     'Skull',
    files_archive:      'Archive',
    files_clip:         'Paperclip',
    files_file:         'Document',
    files_folder_open:  'Open Folder',
    findfriends:        'Find Friends',
    flappy_cloudy:      'Clouds',
    flappy_joystick:    'Joystick',
    flappy_rocket:      'Rocket',
    four_columns:       'Four Columns',
    four_dot:           'Counter',
    four_target:        'Target',
    friends_satellite:  'Satellite',
    friends_scan:       'Scan Area',
    friends_search:     'Find Person',
    garage_bike:        'Bicycle',
    garage_car:         'Car Front',
    garage_truck:       'Truck',
    groups_contact:     'Contact Card',
    groups_person:      'Person',
    groups_round:       'People',
    health_activity:    'Activity',
    health_dumbbell:    'Dumbbell',
    health_pill:        'Pill',
    health_stethoscope: 'Stethoscope',
    home_bed:           'Bed',
    home_building:      'Building',
    home_door:          'Open Door',
    mail_box:           'Mailbox',
    mail_inbox:         'Inbox',
    mail_open:          'Open Envelope',
    map_navigation:     'Navigation',
    map_pin:            'Map Pin',
    map_pinned:         'Pinned Map',
    map_route:          'Route',
    market_basket:      'Basket',
    market_cart:        'Shopping Cart',
    market_package:     'Package',
    market_tag:         'Price Tag',
    message_bubble:     'Speech Bubble',
    message_more:       'Chat Bubble',
    message_send:       'Send Message',
    message_text:       'Text Message',
    music_disc:         'Record',
    music_headphones:   'Headphones',
    music_playlist:     'Playlist',
    music_wave:         'Waveform',
    news_earth:         'Globe',
    news_podcast:       'Podcast',
    news_rss:           'News Feed',
    news_tv:            'News Screen',
    notes_list:         'Checklist',
    notes_notebook:     'Notebook',
    notes_pen:          'Pen',
    pages_book:         'Book',
    pages_bookmark:     'Marked Book',
    pages_scroll:       'Scroll',
    pass_finger:        'Fingerprint',
    pass_key:           'Key',
    pass_lock:          'Lock',
    pass_shield:        'Shield',
    phone_call:         'Phone Call',
    phone_headset:      'Headset',
    phone_incoming:     'Incoming Call',
    phone_outgoing:     'Outgoing Call',
    photogram_film:     'Film Reel',
    photogram_gallery:  'Photo Deck',
    photogram_grid:     'Photo Grid',
    photogram_sparkles: 'Sparkles',
    photos_frame:       'Picture Frame',
    photos_gallery:     'Photo Gallery',
    photos_images:      'Photo Stack',
    radio_antenna:      'Antenna',
    radio_boombox:      'Boombox',
    radio_speaker:      'Speaker',
    radio_tower:        'Radio Tower',
    rail_ticket:        'Ticket',
    rail_track:         'Train Track',
    rail_tram:          'Tram',
    review_half:        'Half Star',
    review_medal:       'Medal',
    review_thumb:       'Thumbs Up',
    ryde_bus:           'Bus',
    ryde_taxi:          'Taxi',
    ryde_waypoints:     'Waypoints',
    safari:             'Safari',
    safari_bookmark:    'Bookmark',
    safari_link:        'Link',
    safari_search:      'Search',
    safari_window:      'Browser Window',
    services_badge:     'Verified Badge',
    services_hammer:    'Hammer',
    services_hardhat:   'Hard Hat',
    settings_cog:       'Cog',
    settings_sliders:   'Sliders',
    settings_toggle:    'Toggle',
    settings_wrench:    'Wrench',
    ship_anchor:        'Anchor',
    ship_sail:          'Sailboat',
    ship_waves:         'Waves',
    ship_wheel:         'Ship Wheel',
    stocks_bars:        'Bar Chart',
    stocks_candles:     'Candlesticks',
    stocks_down:        'Trending Down',
    stocks_line:        'Line Chart',
    streaks_calendar:   'Streak Day',
    streaks_check:      'Day Complete',
    streaks_kindling:   'Campfire',
    vibez_clapper:      'Clapperboard',
    vibez_play:         'Play',
    vibez_tv:           'Television',
    voice_lines:        'Audio Lines',
    voice_mailbox:      'Voicemail',
    voice_vocal:        'Vocal Mic',
    wallet:             'Wallet',
    wallet_card:        'Bank Card',
    wallet_cash:        'Banknote',
    wallet_coin:        'Coin',
    wallet_receipt:     'Receipt',
    weather_cloud:      'Cloud',
    weather_rain:       'Rain',
    weather_snow:       'Snowflake',
    weather_sun:        'Sun',
    wordle_grid:        'Letter Grid',
    wordle_spell:       'Spell Check',
    wordle_type:        'Letters',
};

export function glyphLabel(name: string): string {
    const known = THEME_APPS.find(app => app.icon === name);
    if (known) return known.label;
    return GLYPH_LABELS[name] ?? name.charAt(0).toUpperCase() + name.slice(1);
}

export const APP_ID_PATTERN = /^[a-z0-9][a-z0-9_-]{0,31}$/;

export const RADIUS_SQUIRCLE = 0.276;

export function radiusChoices(): { value: number; label: string }[] {
    return [
        { value: RADIUS_SQUIRCLE, label: t('settings.iconShapeSquircle', 'Squircle') },
        { value: 0.14,            label: t('settings.iconShapeRounded', 'Rounded') },
        { value: 0.5,             label: t('settings.iconShapeCircle', 'Circle') },
        { value: 0.04,            label: t('settings.iconShapeSquared', 'Squared') },
    ];
}

export function textureChoices(): { value: IconTexture; label: string }[] {
    return [
        { value: 'none',    label: t('settings.iconTextureNone', 'None') },
        { value: 'noise',   label: t('settings.iconTextureNoise', 'Grain') },
        { value: 'dots',    label: t('settings.iconTextureDots', 'Dots') },
        { value: 'stripes', label: t('settings.iconTextureStripes', 'Lines') },
    ];
}

export const SWATCHES = [
    '#ffffff', '#f4f4f6', '#d1d1d6', '#8e8e93', '#48484a', '#26262a', '#0a0a0c', '#000000',
    '#ff453a', '#ff6482', '#ff9f0a', '#ffd60a', '#e8dcc4', '#ac8e68', '#8b5e3c', '#5c3d2e',
    '#34c759', '#00c7be', '#5ac8fa', '#0a84ff', '#5e5ce6', '#bf5af2', '#39414f', '#1f3a5f',
];

export interface ThemePreset {
    id:    string;
    label: string;
    hint:  string;
    seed:  IconThemeDraft;
}

export function themePresets(): ThemePreset[] {
    return [
        {
            id:    'flat',
            label: t('settings.iconPresetFlat', 'Flat'),
            hint:  t('settings.iconPresetFlatHint', 'A plain tile in each app colour'),
            seed:  {
                background: { from: 'accent' },
                glyph:      { from: 'fixed', color: '#ffffff' },
            },
        },
        {
            id:    'glass',
            label: t('settings.iconPresetGlass', 'Glass'),
            hint:  t('settings.iconPresetGlassHint', 'Lit and glossy, the classic look'),
            seed:  {
                background: { from: 'accent' },
                glyph:      { from: 'fixed', color: '#ffffff' },
                depth:      true,
            },
        },
        {
            id:    'gradient',
            label: t('settings.iconPresetGradient', 'Gradient'),
            hint:  t('settings.iconPresetGradientHint', 'Each colour fading into shadow'),
            seed:  {
                background:  { from: 'accent' },
                background2: { from: 'accent', toward: '#0f0f12', amount: 0.55 },
                angle:       160,
                gloss:       0.35,
                glyph:       { from: 'fixed', color: '#ffffff' },
            },
        },
        {
            id:    'neon',
            label: t('settings.iconPresetNeon', 'Neon'),
            hint:  t('settings.iconPresetNeonHint', 'Black tiles with a lit outline'),
            seed:  {
                background: { from: 'fixed', color: '#0a0a0c' },
                glyph:      { from: 'accent', toward: '#ffffff', amount: 0.24 },
                border:     { color: { from: 'accent' }, width: 1 },
                glow:       0.7,
                saturation: 1.3,
            },
        },
        {
            id:    'paper',
            label: t('settings.iconPresetPaper', 'Paper'),
            hint:  t('settings.iconPresetPaperHint', 'Off-white cards with a printed grain'),
            seed:  {
                background: { from: 'fixed', color: '#f4f4f6' },
                glyph:      { from: 'accent', toward: '#1b1b1f', amount: 0.36 },
                radius:     0.14,
                texture:    'dots',
                border:     { color: { from: 'fixed', color: '#d1d1d6' }, width: 1 },
                glyphScale: 0.92,
            },
        },
        {
            id:    'ink',
            label: t('settings.iconPresetInk', 'Ink'),
            hint:  t('settings.iconPresetInkHint', 'Every app colour drained to graphite'),
            seed:  {
                background:  { from: 'accent', toward: '#141418', amount: 0.5 },
                glyph:       { from: 'fixed', color: '#f5f5f7' },
                saturation:  0,
                radius:      0.04,
                glyphWeight: 2.2,
            },
        },
    ];
}
